import Head from "next/head";
import Image from "next/image";
import useAspidaSWR from "@aspida/swr";
import aspida from "@aspida/fetch";
import api from "../api/$api";
import styles from "../styles/Home.module.css";

const client = api(
  aspida(fetch, {
    baseURL: "https://petstore3.swagger.io/api/v3",
    throwHttpErrors: true,
  })
);

export default function Home() {
  const { data, error } = useAspidaSWR(client.pet.findByStatus, {
    query: { status: "sold" },
  });

  if (error) return <div>failed to load</div>;
  if (!data) return <div>loading...</div>;

  console.log(data);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{" "}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <ul>
          {data.map((pet) => (
            <li key={pet.id}>{pet.name}</li>
          ))}
        </ul>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
